
#Settings affecting the logical server side.
[server]

	#Miscellaneous settings
	[server.miscellaneous]
		#Enables experimental features. Use at own risk.
		with_experimental = false
		#Enable detailed logging of the config values and resulting calculations in each mod feature config.
		with_config_logging = false

	#Tweak settings
	[server.tweaks]
		#Sets how probable it is that a Red Ant Hive drops when manually mining Redstone Ore. The value 0 disables drops from Redstone mining (you need to add your own recipe in a data pack).
		#Range: 0 ~ 20
		hive_drop_chance_percent = 3
		#Sets how fast the ant processing part of work process is (in percent).
		#Range: 50 ~ 150
		hive_processing_speed_percent = 100
		#Sets how long the Red Sugar boost lasts (in seconds).
		#Range: 1 ~ 60
		hive_sugar_boost_time_s = 5
		#Sets how long it takes (seconds, in average) to generate one new ant in a hive.
		#Range: 60 ~ 600
		hive_growth_period_s = 120
		#Tunes the internal delay between animals are fed. The value 0 disables animal feeding.
		#Range: 0 ~ 150
		hive_animal_feeding_speed_percent = 100
		#Tunes the internal delay between harvesting crops. The value 0 disables harvesting.
		#Range: 0 ~ 150
		hive_farming_speed_percent = 100

#Settings where you can explicitly define which tools or other control items the Hive knows.
[hive_control_items]
	#Items that can be placed into the Hive control slot to activate ~normal crafting~.
	crafting_tables = ["minecraft:crafting_table"]
	#Items that can be placed into the Hive control slot to activate ~smelting or cooking~.
	furnaces = ["minecraft:furnace"]
	#Items that can be placed into the Hive control slot to activate ~fast smelting~.
	blast_furnaces = ["minecraft:blast_furnace"]
	#Items that can be placed into the Hive control slot to activate ~fast cooking~.
	smokers = ["minecraft:smoker"]
	#Items that can be placed into the Hive control slot to activate ~composting~.
	composters = ["minecraft:composter"]
	#Items that can be placed into the Hive control slot to activate ~potion brewing~.
	brewing_stands = ["minecraft:brewing_stand"]
	#Items that can be placed into the Hive control slot to activate ~disenchanting~.
	grindstones = ["minecraft:grindstone"]
	#Items that can be placed into Hive slots to activate ~item pass through (control slot), item input drawing, and item output inserting~.
	hoppers = ["minecraft:hopper"]
	#Items that can be placed into the Hive output slot to activate ~item drop output (soft eject)~.
	droppers = ["minecraft:dropper"]
	#Items that can be placed into the Hive output slot to activate ~item dispense output (fast eject)~.
	dispensers = ["minecraft:dispenser"]
	#Items that can be placed into the Hive control slot to activate ~animal or plant shearing~.
	shears = ["minecraft:shears"]
	#Items that can be placed into the Hive control slot to activate ~farmning~.
	hoes = ["minecraft:iron_hoe", "minecraft:diamond_hoe", "minecraft:netherite_hoe"]
	#Items that can be placed into the Hive control slot to activate ~tree chopping~.
	axes = ["minecraft:iron_axe", "minecraft:diamond_axe", "minecraft:netherite_axe"]
	#Items that can be placed into the Hive control slot to activate ~block breaking~.
	pickaxes = ["minecraft:iron_pickaxe", "minecraft:diamond_pickaxe", "minecraft:netherite_pickaxe"]

