
#Mystic's Biomes
#Common Config Center
["World Gen"]
	#The higher the number, the more common the biomes will be.
	#Default: 4
	"Biome Region Weight" = 4
	#Determines if each biome will generate or not.
	"Strawberry Fields" = true
	"Bamboo Blossom Forest" = true
	"Lavender Meadow" = true
	"Autumnal Grove" = true

["Animal Spawns"]
	#Biomes an animal can spawn in.
	#Values can include modded biomes and biome tags.
	"Rainbow Chickens" = ["minecraft:plains", "minecraft:forest", "minecraft:flower_forest"]

