
[origins]

	[origins."origins:enderian"]
		enabled = true
		"origins:throw_ender_pearl" = true
		"origins:water_vulnerability" = true
		"origins:pumpkin_hate" = true
		"origins:extra_reach" = true
		"origins:ender_particles" = true
		"origins:damage_from_potions" = true

	[origins."origins:feline"]
		enabled = true
		"origins:fall_immunity" = true
		"origins:sprint_jump" = true
		"origins:velvet_paws" = true
		"origins:nine_lives" = true
		"origins:weak_arms" = true
		"origins:scare_creepers" = true
		"origins:cat_vision" = true

	[origins."origins:elytrian"]
		enabled = true
		"origins:elytra" = true
		"origins:launch_into_air" = true
		"origins:aerial_combatant" = true
		"origins:light_armor" = true
		"origins:claustrophobia" = true
		"origins:more_kinetic_damage" = true

	[origins."dragon_origins:green_dragon_origin"]
		enabled = true
		"dragon_origins:good_neighboer" = true
		"dragon_origins:green" = true
		"dragon_origins:elytra" = true
		"dragon_origins:white_teeth" = true
		"dragon_origins:vegie" = true
		"dragon_origins:food" = true
		"dragon_origins:size" = true
		"dragon_origins:emerald" = true
		"dragon_origins:droar" = true
		"dragon_origins:advancement" = true

	[origins."origins_dd:meran"]
		enabled = true
		"origins_dd:meran/description" = true
		"origins_dd:meran/gills" = true
		"origins_dd:meran/aqua_affinity" = true
		"origins_dd:meran/particles" = true

	[origins."dragon_origins:cookie"]
		enabled = true
		"dragon_origins:canibalism" = true
		"dragon_origins:spillage" = true
		"dragon_origins:advancement" = true

	[origins."dragon_origins:kraken"]
		enabled = true
		"dragon_origins:kraken/bigger_kraken" = true
		"dragon_origins:kraken/tentacles" = true
		"dragon_origins:kraken/grapple" = true
		"dragon_origins:kraken/grappledesc" = true
		"dragon_origins:kraken/grappletp" = true
		"origins:air_from_potions" = true
		"origins:aquatiq" = true
		"origins:aqua_affinity" = true
		"origins:more_exhaustion" = true
		"origins:carnivore" = true
		"origins:water_vision" = true
		"origins:conduit_power_on_land" = true
		"origins:like_water" = true
		"origins:water_breathing" = true
		"dragon_origins:advancement" = true

	[origins."dragon_origins:lorax"]
		enabled = true
		"dragon_origins:lorax/phase" = true
		"dragon_origins:lorax/no_tree_chopping" = true
		"dragon_origins:lorax/size" = true
		"dragon_origins:lorax/friendly" = true
		"dragon_origins:lorax/marshmellow" = true
		"dragon_origins:lorax/food" = true
		"dragon_origins:advancement" = true

	[origins."dragon_origins:mini"]
		enabled = true
		"dragon_origins:speed" = true
		"dragon_origins:size2" = true
		"origins:fall_immunity" = true
		"origins:climbing" = true
		"dragon_origins:haste" = true
		"origins:no_shield" = true
		"dragon_origins:less_hp" = true
		"dragon_origins:speedswim" = true
		"dragon_origins:speed_boost" = true
		"origins:carnivore" = true
		"dragon_origins:slow" = true
		"dragon_origins:jump_boost" = true
		"dragon_origins:advancement" = true

	[origins."origins:phantom"]
		enabled = true
		"origins:phantomize" = true
		"origins:translucent" = true
		"origins:phasing" = true
		"origins:invisibility" = true
		"origins:burn_in_daylight" = true
		"origins:hunger_over_time" = true
		"origins:fragile" = true
		"origins:phantomize_overlay" = true

	[origins."dragon_origins:test"]
		enabled = true
		"dragon_origins:test/invis_temp" = true
		"dragon_origins:test/heal" = true
		"dragon_origins:test/lightning" = true
		"dragon_origins:test/air_swim" = true
		"dragon_origins:test/dimension" = true
		"dragon_origins:advancement" = true

	[origins."origins:blazeborn"]
		enabled = true
		"origins:fire_immunity" = true
		"origins:nether_spawn" = true
		"origins:burning_wrath" = true
		"origins:hotblooded" = true
		"origins:water_vulnerability" = true
		"origins:flame_particles" = true
		"origins:damage_from_snowballs" = true
		"origins:damage_from_potions" = true

	[origins."origins:avian"]
		enabled = true
		"origins:slow_falling" = true
		"origins:fresh_air" = true
		"origins:like_air" = true
		"origins:tailwind" = true
		"origins:lay_eggs" = true
		"origins:vegetarian" = true

	[origins."origins_dd:fireborn"]
		enabled = true
		"origins_dd:fireborn/description" = true
		"origins_dd:fireborn/fire_immunity" = true
		"origins_dd:fireborn/lava_agility" = true
		"origins_dd:fireborn/particles" = true

	[origins."origins_dd:golemlike"]
		enabled = true
		"origins_dd:golemlike/description" = true
		"origins_dd:golemlike/massive" = true
		"origins_dd:golemlike/powerful" = true

	[origins."dragon_origins:cyborg"]
		enabled = true
		"dragon_origins:metal_skin" = true
		"dragon_origins:water" = true
		"dragon_origins:xtrajump" = true
		"dragon_origins:fire_immunity" = true
		"dragon_origins:no_armor" = true
		"dragon_origins:fall_dam" = true
		"dragon_origins:night_v" = true
		"dragon_origins:advancement" = true

	[origins."dragon_origins:panda"]
		enabled = true
		"dragon_origins:panda/food" = true
		"dragon_origins:panda/food_dis" = true
		"dragon_origins:kraken/langtest" = true
		"origins:vegetarian" = true
		"dragon_origins:advancement" = true

	[origins."dragon_origins:red_dragon"]
		enabled = true
		"origins:fire_immunity" = true
		"origins:nether_spawn" = true
		"origins:burning_wrath" = true
		"origins:water_vulnerability" = true
		"origins:hotblooded" = true
		"dragon_origins:freeze" = true
		"dragon_origins:size69" = true
		"dragon_origins:wreckless" = true
		"origins:carnivore" = true
		"dragon_origins:advancement" = true

	[origins."dragon_origins:pirate"]
		enabled = true
		"dragon_origins:pirate/hook" = true
		"dragon_origins:pirate/eye_patch" = true
		"dragon_origins:pirate/swim_speed" = true
		"dragon_origins:pirate/home" = true
		"dragon_origins:pirate/shiny" = true
		"dragon_origins:advancement" = true

	[origins."origins_dd:arthropodic"]
		enabled = true
		"origins_dd:arthropodic/description" = true
		"origins_dd:arthropodic/climbing" = true
		"origins_dd:arthropodic/faster_climbing" = true

	[origins."dragon_origins:druid"]
		enabled = true
		"dragon_origins:f_buf" = true
		"dragon_origins:nether2" = true
		"dragon_origins:hot_debuf" = true
		"dragon_origins:vegie3" = true
		"dragon_origins:roots" = true
		"dragon_origins:roots2" = true
		"dragon_origins:roots3" = true
		"dragon_origins:roots4" = true
		"dragon_origins:heal2" = true
		"dragon_origins:regen" = true
		"dragon_origins:plant_v" = true
		"dragon_origins:green2" = true
		"dragon_origins:hunger" = true
		"dragon_origins:advancement" = true

	[origins."dragon_origins:yang"]
		enabled = true
		"dragon_origins:yinyang/yang/yintransform" = true
		"dragon_origins:yinyang/yang/cloud" = true
		"dragon_origins:yinyang/yang/posess" = true
		"dragon_origins:yinyang/yang/transparency1" = true
		"dragon_origins:yinyang/yang/dayweak" = true
		"dragon_origins:yinyang/yang/invis_temp" = true
		"dragon_origins:advancement" = true

	[origins."origins_dd:avine"]
		enabled = true
		"origins_dd:avine/description" = true
		"origins_dd:avine/smaller" = true
		"origins_dd:avine/agile_airborne" = true

	[origins."origins:human"]
		enabled = true

	[origins."origins_dd:human"]
		enabled = true
		"origins_dd:human/description" = true
		"origins_dd:human/lucky" = true

	[origins."dragon_origins:sand_larvae"]
		enabled = true
		"dragon_origins:sand/sand_larvae/air_swim" = true
		"dragon_origins:sand/sand_larvae/advancement" = true
		"dragon_origins:sand/sand_larvae/hp" = true
		"dragon_origins:sand/sand_larvae/size" = true
		"dragon_origins:sand/sand_larvae/bite" = true
		"dragon_origins:sand/sand_larvae/spit" = true
		"dragon_origins:sand/sand_larvae/sand_confidene" = true
		"dragon_origins:sand/sand_larvae/desert" = true
		"dragon_origins:advancement" = true

	[origins."origins:shulk"]
		enabled = true
		"origins:shulker_inventory" = true
		"origins:natural_armor" = true
		"origins:strong_arms" = true
		"origins:strong_arms_break_speed" = true
		"origins:no_shield" = true
		"origins:more_exhaustion" = true

	[origins."dragon_origins:magic_fly"]
		enabled = true
		"dragon_origins:vegie2" = true
		"dragon_origins:fairy_wings" = true
		"dragon_origins:easy_travel" = true
		"dragon_origins:size3" = true
		"dragon_origins:slow" = true
		"origins:fall_immunity" = true
		"dragon_origins:6hp" = true
		"dragon_origins:no_swords" = true
		"dragon_origins:iron_golem" = true
		"dragon_origins:heal" = true
		"dragon_origins:no_combat" = true
		"dragon_origins:hot_debuf" = true
		"dragon_origins:nether" = true
		"dragon_origins:hunger" = true
		"dragon_origins:advancement" = true

	[origins."origins:merling"]
		enabled = true
		"origins:water_breathing" = true
		"origins:water_vision" = true
		"origins:aqua_affinity" = true
		"origins:swim_speed" = true
		"origins:like_water" = true
		"origins:aquatic" = true
		"origins:conduit_power_on_land" = true
		"origins:air_from_potions" = true

	[origins."origins_dd:stalwart"]
		enabled = true
		"origins_dd:stalwart/description" = true
		"origins_dd:stalwart/taller" = true
		"origins_dd:stalwart/efficient" = true

	[origins."dragon_origins:undead"]
		enabled = true
		"dragon_origins:zombie" = true
		"dragon_origins:daylight" = true
		"dragon_origins:hugs" = true
		"dragon_origins:body" = true
		"dragon_origins:body_" = true
		"dragon_origins:gloom" = true
		"dragon_origins:undead" = true
		"dragon_origins:unnerving" = true
		"dragon_origins:attacker" = true
		"dragon_origins:target" = true
		"dragon_origins:join_team" = true
		"dragon_origins:create_team" = true
		"dragon_origins:summon" = true
		"dragon_origins:shovel" = true
		"dragon_origins:stone_sword" = true
		"dragon_origins:advancement" = true

	[origins."origins:arachnid"]
		enabled = true
		"origins:climbing" = true
		"origins:master_of_webs" = true
		"origins:carnivore" = true
		"origins:fragile" = true
		"origins:arthropod" = true

	[origins."dragon_origins:mimic"]
		enabled = true
		"dragon_origins:mimic/toggle" = true
		"dragon_origins:mimic/toggle2" = true
		"dragon_origins:mimic/display" = true
		"origins:nine_lives" = true
		"dragon_origins:advancement" = true

	[origins."dragon_origins:yin"]
		enabled = true
		"dragon_origins:yinyang/yin/yangtransform" = true
		"dragon_origins:yinyang/yin/heal" = true
		"dragon_origins:test/lightning" = true
		"dragon_origins:yinyang/yin/transparency" = true
		"dragon_origins:yinyang/yin/darkweak" = true
		"dragon_origins:advancement" = true

	[origins."origins_dd:feral"]
		enabled = true
		"origins_dd:feral/description" = true
		"origins_dd:feral/little" = true
		"origins_dd:feral/hungry" = true
		"origins_dd:feral/nimble" = true

	[origins."dragon_origins:necromancer"]
		enabled = true
		"dragon_origins:gloom" = true
		"dragon_origins:gloom2" = true
		"dragon_origins:mysterous" = true
		"dragon_origins:emume" = true
		"dragon_origins:summon/sz_summon" = true
		"dragon_origins:summon/a_summon" = true
		"dragon_origins:summon/d_summon" = true
		"dragon_origins:cloak" = true
		"dragon_origins:advancement" = true

