#How many blocks should be mined at once?
#Range: 2 ~ 8192
blocklimit = 16
#If set to true, you need the correct tool to break the blocks.
requiresCorrectTool = true
#If set to true, blocks will only be found on the 6 sides on each block.
#It does not mean that only the 6 blocks around will be mined, but only these will be added to the list which should be mined.
disableDiagonals = false
#If set to true, the player will be able to change shapes.
allowShapeSelection = true
#Defines which blocks can be mined with Excavar
#Allowed Values: ORES, LOGS, ORES_AND_LOGS, ALL
allowedBlocks = "ALL"
#A list of tools which aren't allowed.
#You can use "*" to define a wildcard, e.g. "minecraft:*_pickaxe" will add all vanilla pickaxes to the list.
forbiddenItems = ["botania:terra_axe", "botania:terra_pick"]

